variables:
  NODE_VERSION: "14.15-alpine"

cache:
  paths:
    - node_modules

get-fact:project:info:
  image: private.nexus-regs.docker:8086/node:${NODE_VERSION}
  script:
    - export PROJECT_NAME=$(node -e "console.log(require('./package.json').name);")
    - export PROJECT_GROUP_ID=$(node -e "console.log(require('./package.json').groupId);")    
    - export PROJECT_VERSION=$(node -e "console.log(require('./package.json').version);")
    - echo "PROJECT_NAME=$PROJECT_NAME" >> deploy.env
    - echo "PROJECT_GROUP_ID=$PROJECT_GROUP_ID" >> deploy.env
    - echo "PROJECT_VERSION=$PROJECT_VERSION" >> deploy.env
    - echo "CI_PARENT_PROJECT_NAME=${PROJECT_NAME}" >> deploy.env
    - echo "CI_PARENT_PROJECT_GROUP_ID=${PROJECT_GROUP_ID}" >> deploy.env
    - echo "CI_PARENT_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA}" >> deploy.env
    - echo "CI_PARENT_PIPELINE_PROJECT_ID=${PROJECT_NAME}" >> deploy.env
  artifacts:
    name: $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA
    reports:
      dotenv: deploy.env

.build-ng:
  image: private.nexus-regs.docker:8086/node:${NODE_VERSION}
  variables:
    NG_CLI_EXEC: "./node_modules/@angular/cli/bin/ng"
    NG_MEMORY_HEAP: "--max_old_space_size=2048"
    BUILD_OUTPUT_PATH: "--output-path=dist"
    BUILD_CONFIGURATION: "--configuration=production"
  before_script:
    - cat $NPM_PROXY > .npmrc
  script:
    - apk add --no-cache git # install git required by install package
    - npm install @angular-devkit/build-angular --silent
    - npm install --silence
    - node $NG_MEMORY_HEAP $NG_CLI_EXEC build $BUILD_OUTPUT_PATH --aot --build-optimizer $BUILD_CONFIGURATION --common-chunk --optimization --source-map --stats-json
  artifacts:
    name: $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA
    paths:
      - dist/*